# This file is here to facilitate development/testing.
# See the readme for a list of configuration options.
# Copy the .env.example and add in your S3 credentials.
# $ docker compose up -d --build --force-recreate

services:
  test_image:
    build: ./test_image
    volumes:
      - data:/data

  backup:
    build: .
    env_file: .env
    volumes:
      - data:/data/testdir
    environment:
      BACKUP_NAME: backup-test
      SCHEDULE: '* * * * *'
      BACKUP_KEEP_DAYS: 7
      PASSPHRASE: passphrase
      S3_PREFIX: backup-test

volumes:
  data:
